sudo: false
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

language: scala
matrix:
  include:
    # Test Scala 2.10 and 2.11 with both JDK 6 and 8
    - scala: 2.10.7
      jdk: openjdk7
    - scala: 2.11.8
      jdk: openjdk7
    - scala: 2.10.7
      jdk: oraclejdk8
    - scala: 2.11.8
      jdk: oraclejdk8
    # Scala 2.12+ only supports JDK 8+
    - scala: 2.12.4
      jdk: oraclejdk8
    - scala: 2.12.6
      jdk: oraclejdk10

sbt_args: "'set resolvers += \"Sonatype OSS Snapshots\" at \"https://oss.sonatype.org/content/repositories/snapshots\"'"

before_script:
  - export JAVA7_HOME=$(jdk_switcher home openjdk7)



