sudo: false
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

language: scala
matrix:
  include:
    # Test Scala 2.10 and 2.11 with both JDK 6 and 8
    - scala: 2.10.6
      jdk: oraclejdk7
    - scala: 2.11.8
      jdk: oraclejdk7
    - scala: 2.10.6
      jdk: oraclejdk8
    - scala: 2.11.8
      jdk: oraclejdk8
    # Scala 2.12+ only supports JDK 8+
    - scala: 2.12.0
      jdk: oraclejdk8

sbt_args: "'set resolvers += \"Sonatype OSS Snapshots\" at \"https://oss.sonatype.org/content/repositories/snapshots\"'"

before_script:
  - export JAVA7_HOME=$(jdk_switcher home oraclejdk7)

env:
  global:
    - secure: "EAnt75OQNWHWvZomCAb8G5IdqcVMR0NqzngOKFOeSsjaB2CFVtfYoAq3dzp0utBqiOnWe1l5TCmcFUzMrkw+nuWbScKXYyiE6268LcA02/JBkAxnOcOo/6/xVh3oX0NhrBN5BSkJF5Hz5ffDXZArGM30s7FFhiijcmuo7J4/o0E="
    - secure: "LYBEb/y1T1yb3CsNZe0Q+yUUqhYblvW8lMWXxy/Ozho+0FHA67TzCpGO9SOBVvp0Cewu2BzOeW6/Z9DZfOKL88zSvXT9HjSPRc7MEd17+LnqeTNmxTSz3RztXnyYqs/YPi7se+HscwYytnJKS611KZ0m1QkI4IrUcBS0Xib6ZhQ="

